server:
  port: 9999

spring:
  datasource:
    username: root
    password: 970103
    url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


  redis:
    host: 172.20.252.197
    port: 6379
    password: 123321
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 85
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.lwy: debug